### ISSUE TITLE
Problems with Android

### ISSUE THREAD

**Issue by demetrio812** [triniwiz/nativescript-image-cache-it#17]
Hello,
I'm testing the component, it looks great on iOS but on Android I'm getting a lot of problems and it's unusable.

I'm using the component inside RadListViews.

Getting different errors, I've tried to understand if there is a specific cause but it doesn't seems to be related to a specific thing:

Here the errors I'm having in different parts of the app:

```
ERROR Error: java.lang.IllegalStateException: Center crop requires calling resize with positive width and height.
JS:     com.squareup.picasso.Request$Builder.build(Request.java:496)
JS:     com.squareup.picasso.RequestCreator.createRequest(RequestCreator.java:758)
JS:     com.squareup.picasso.RequestCreator.into(RequestCreator.java:709)
JS:     com.squareup.picasso.RequestCreator.into(RequestCreator.java:665)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:957)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:941)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:933)
JS:     com.tns.gen.com.telerik.widget.list.ListViewAdapter_frnal_ts_helpers_l58_c38__ListViewAdapter.onBindViewHolder(ListViewAdapter_frnal_ts_helpers_l58_c38__ListViewAdapter.java:26)
JS:     com.telerik.widget.list.ListViewWrapperAdapter.onBindViewHolder(ListViewWrapperAdapter.java:247)
JS:     com.telerik.widget.list.ListViewWrapperAdapter.onBindViewHolder(ListViewWrapperAdapter.java:20)
JS:     android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6400)
JS:     android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6433)
JS:     android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5377)
JS:     android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5640)
JS:     android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5482)
JS:     android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5478)
JS:     android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2215)
JS:     android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1542)
JS:     android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1502)
JS:     android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
JS:     android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3625)
JS:     android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3354)
JS:     android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3886)
JS:     com.telerik.widget.list.RadListView.onLayout(RadListView.java:587)
JS:     android.view.View.layout(View.java:19659)
```

```
JS: ERROR TypeError: Cannot read property 'placeholder' of undefined
JS: ERROR CONTEXT [object Object]
JS: ERROR TypeError: Cannot read property 'placeholder' of undefined
JS: ERROR CONTEXT [object Object]
JS: ERROR TypeError: Cannot read property 'placeholder' of undefined
JS: ERROR CONTEXT [object Object]
JS: ERROR TypeError: Cannot read property 'placeholder' of undefined
JS: ERROR CONTEXT [object Object]
JS: ERROR TypeError: Cannot read property 'placeholder' of undefined
JS: ERROR CONTEXT [object Object]
JS: ERROR TypeError: Cannot read property 'placeholder' of undefined
JS: ERROR CONTEXT [object Object]
JS: ERROR TypeError: Cannot read property 'placeholder' of undefined
JS: ERROR CONTEXT [object Object]
JS: ERROR TypeError: Cannot read property 'placeholder' of undefined
JS: ERROR CONTEXT [object Object]
JS: ERROR TypeError: Cannot read property 'placeholder' of undefined
JS: ERROR CONTEXT [object Object]
System.err: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 8(offset:8).state:9
System.err:     at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5546)
System.err:     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5482)
System.err:     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5478)
System.err:     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2215)
System.err:     at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
System.err:     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1502)
System.err:     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
System.err:     at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
System.err:     at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3625)
System.err:     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3354)
System.err:     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3886)
System.err:     at com.telerik.widget.list.RadListView.onLayout(RadListView.java:587)
System.err:     at android.view.View.layout(View.java:19659)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6075)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err:     at android.view.View.layout(View.java:19659)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6075)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
System.err:     at android.view.View.layout(View.java:19659)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6075)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:169)
System.err:     at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:123)
System.err:     at android.view.View.layout(View.java:19659)
```

Any idea?

I'm sorry I'm not very helpful, if you need it I can create a demo project to reproduce the issue...

Let me know...

Thanks,
Dem

**Comment by triniwiz** [comment]
I will need more info that this

**Comment by demetrio812** [comment]
I know, will try to create a project to reproduce it and send, cheers

**Comment by bradmartin** [comment]
first run for me:

```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onCreateViewHolder failed

TypeError: Cannot read property 'get' of undefined
File: "file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/nativescript-image-cache-it/image-cache-it.js, line: 16, column: 51

StackTrace: 
	Frame: function:'ImageCacheIt.createNativeView', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/nativescript-image-cache-it/image-cache-it.js', line: 16, column: 52
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 412, column: 35
	Frame: function:'', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
	Frame: function:'', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 456, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 699, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 455, column: 14
	Frame: function:'ViewBase._addViewCore', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 357, column: 18
	Frame: function:'ViewBase._addView', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 346, column: 14
	Frame: function:'ListViewAdapter.onCreateViewHolder', file:'file:///data/data/com.jsoftllc.loopmein/files/app/tns_modules/nativescript-pro-ui/listview/listview.js', line: 104, column: 26


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.gen.com.telerik.widget.list.ListViewAdapter_frnal_ts_helpers_l58_c38__ListViewAdapter.onCreateViewHolder(ListViewAdapter_frnal_ts_helpers_l58_c38__ListViewAdapter.java:13)
	at com.telerik.widget.list.SwipeActionsBehavior.createViewHolder(SwipeActionsBehavior.java:159)
	at com.telerik.widget.list.ListViewWrapperAdapter.onCreateViewHolder(ListViewWrapperAdapter.java:454)
	at com.telerik.widget.list.ListViewWrapperAdapter.onCreateViewHolder(ListViewWrapperAdapter.java:20)
	at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6411)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5597)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5482)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5478)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2215)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1542)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1502)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3625)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3354)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3886)
	at com.telerik.widget.list.RadListView.onLayout(RadListView.java:587)
	at android.view.View.layout(View.java:19590)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:614)
	at android.view.View.layout(View.java:19590)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19590)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
	at android.view.View.layout(View.java:19590)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
	at org.nativescript.widgets.AbsoluteLayout.onLayout(AbsoluteLayout.java:76)
	at android.view.View.layout(View.java:19590)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
	at android.view.View.layout(View.java:19590)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
	at org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73)
	at android.view.View.layout(View.java:19590)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19590)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
	at android.view.View.layout(View.java:19590)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:758)
	at android.view.View.layout(View.java:19590)
	at android.view.ViewGroup.layout(ViewGroup.java:6053)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2484)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2200)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

page:

```xml
<Page 
    xmlns="http://schemas.nativescript.org/tns.xsd" 
    xmlns:SP="components/store-picker" 
    xmlns:Input="components/input" 
    xmlns:i="nativescript-image-cache-it" 
    xmlns:fresco="nativescript-fresco" 
    xmlns:FAB="nativescript-floatingactionbutton" 
    xmlns:dropdown="nativescript-drop-down" 
    xmlns:lv="nativescript-pro-ui/listview" loaded="onLoaded" unloaded="{{ onPageUnloaded }}" actionBarHidden="true" backgroundSpanUnderStatusBar="true">
    <AbsoluteLayout height="100%" width="100%">
        <GridLayout height="100%" width="100%" rows="80, auto, *, auto" columns="*">
            <Label row="2" verticalAlignment="middle" class="text-center m-t-10" text="{{ inventoryListViewInfoText }}" visibility="{{ inventoryListViewInfoText != '' ? 'visible' : 'collapsed' }}" textWrap="true" />
            <lv:RadListView row="1" rowSpan="2" id="inventoryListView" paddingTop="{{ headerHeight }}" items="{{ inventoryListItems }}" loadOnDemandMode="Auto" loadMoreDataRequested="{{ onLoadMoreItemsRequested }}" selectionBehavior="None" itemSelected="{{ onInventoryItemTap }}" pullToRefresh="true" pullToRefreshInitiated="{{ onPullToRefreshInitiated }}" visibility="{{ inventoryListItems.length >= 1 ? 'visible' : 'collapse' }}" itemSwipeProgressStarted="{{ onSwipeCellStarted }}" swipeActions="true">
                <lv:RadListView.itemTemplate>
                    <GridLayout tap="{{ onInventoryItemTap }}" minHeight="70" rows="auto, *, auto" columns="130, *, auto" class="list-group-item">
                        <i:ImageCacheIt class="list-image" placeHolder="res://icon" stretch="aspectFit" borderRadius="4" width="100" height="100" imageUri="{{ photo_url }}"/>
                     
```
and previously the Image: `<Image class="list-image" src="{{ photo_url }}" row="0" col="0" rowSpan="4" stretch="aspectFill" />` in same location was working

currently looking to see what's going on

**Comment by bradmartin** [comment]
I now see this might be me being an idiot not uninstalling the old apk and rebuilding 🙈 🙉 - will update soon.

*UPDATE* - all good in RLV now.

**Comment by bradmartin** [comment]
Okay, I have something here:

`Error: java.lang.IllegalStateException: Center inside requires calling resize with positive width and height.`

with only

```xml
<i:ImageCacheIt stretch="aspectFit" imageUri="~/images/user.png" />
```

My hunch was the `stretch` value, removing it and no illegalArg exception so this seems to be similar to the original issue comment @triniwiz maybe that'll help you understand what's happening 👍 

May not be so much an issue as it is making sure it's documented and then maybe a simple safe guard when the `stretch` prop is being set

**Comment by bradmartin** [comment]
`aspectFill` throws the center crop ex.
`aspectFit` throws the center inside ex.
`fill` does not throw without dimensions and of course same for `none` 

**UPDATE** 

In the demo app you can replace one of the template imageCacheIt with `<i:ImageCacheIt stretch="aspectFill" imageUri="{{url}}"/>` and it will throw the native illegal arg exceptions (same with `aspectFit`)

@demetrio812 do you have anything similar to above ^^^

**Comment by bradmartin** [comment]
Think I've found fix, will get a PR in the works 👍

**Comment by demetrio812** [comment]
Thanks @bradmartin sorry I didn't have the time to create a test project but I will check your fix!! Thanks for your time!!!
