### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by alexrainman** [triniwiz/nativescript-image-cache-it#37]
### Which platform(s) does your issue occur on?

- Android (API26) emulator

### StackTrace:

```
System.err: com.tns.NativeScriptException: 

System.err: Calling js method onCreateViewHolder failed
System.err: 

System.err: TypeError: Cannot read property 'get' of undefined

System.err: File: "file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-image-cache-it/image-cache-it.js, line: 16, column: 69
System.err: 

System.err: StackTrace: 
System.err: 	Frame: function:'ImageCacheIt.createNativeView', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-image-cache-it/image-cache-it.js', line: 16, column: 70
System.err: 	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 491, column: 31

System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 19

System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14

System.err: 	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 532, column: 14
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 19
System.err: 	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err: 	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14

System.err: 	Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 532, column: 14
System.err: 	Frame: function:'ViewBase._addViewCore', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 431, column: 18
System.err: 	Frame: function:'ViewBase._addView', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 420, column: 14
System.err: 	Frame: function:'ListViewAdapter.onCreateViewHolder', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-ui-listview/ui-listview.js', line: 132, column: 19
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:983)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:967)

System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:959)

System.err: 	at com.tns.gen.com.telerik.widget.list.ListViewAdapter_listview_82_32_ListViewAdapter.onCreateViewHolder(ListViewAdapter_listview_82_32_ListViewAdapter.java:23)
System.err: 	at com.telerik.widget.list.ListViewWrapperAdapter.onCreateListViewHolder(ListViewWrapperAdapter.java:465)

System.err: 	at com.telerik.widget.list.ListViewAdapterBase.onCreateViewHolder(ListViewAdapterBase.java:145)
System.err: 	at com.telerik.widget.list.ListViewAdapterBase.onCreateViewHolder(ListViewAdapterBase.java:22)

System.err: 	at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6794)

System.err: 	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975)
System.err: 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)

System.err: 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
System.err: 	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)

System.err: 	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)

System.err: 	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)

System.err: 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
System.err: 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
System.err: 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)

System.err: 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)

System.err: 	at com.telerik.widget.list.RadListView.onLayout(RadListView.java:589)
System.err: 	at android.view.View.layout(View.java:19590)

System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)

System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err: 	at android.view.View.layout(View.java:19590)

System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:169)

System.err: 	at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:123)
System.err: 	at android.view.View.layout(View.java:19590)

System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)

System.err: 	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:354)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)

System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73)
System.err: 	at android.view.View.layout(View.java:19590)

System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)

System.err: 	at android.view.View.layout(View.java:19590)

System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
System.err: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)

System.err: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
System.err: 	at android.view.View.layout(View.java:19590)

System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)

System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err: 	at android.view.View.layout(View.java:19590)

System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
System.err: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
System.err: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
System.err: 	at android.view.View.layout(View.java:19590)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:758)
System.err: 	at android.view.View.layout(View.java:19590)

System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6053)

System.err: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2484)

System.err: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2200)
System.err: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)

System.err: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)

System.err: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)

System.err: 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
System.err: 	at android.view.Choreographer.doFrame(Choreographer.java:658)

System.err: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
System.err: 	at android.os.Handler.handleCallback(Handler.java:789)

System.err: 	at android.os.Handler.dispatchMessage(Handler.java:98)
System.err: 	at android.os.Looper.loop(Looper.java:164)

System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)

System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by alexrainman** [comment]
The problem is in this line of code:

```ts
this.picasso = com.squareup.picasso.provider.PicassoProvider.get();
```

**Comment by triniwiz** [comment]
That happens when you are unable to get the provider package i'll update the plugin to use a local version since this issue happens at random

**Comment by alexrainman** [comment]
That was a quick response. Please let me know when you release the update. Thanks.

**Comment by alexrainman** [comment]
One question: is there a reason your plugin is using Picasso 3.0.0-SNAPSHOT instead of latest stable release?

From their website, there's only one gradle dependency:

```
implementation 'com.squareup.picasso:picasso:2.71828'
```

**Comment by triniwiz** [comment]
The last release was `2.71828` and 3.0 although not released works great the only issue i've seen is this

**Comment by alexrainman** [comment]
Is there a workaround i can use while you release the update?

**Comment by triniwiz** [comment]
Usually nuking the project helps

**Comment by alexrainman** [comment]
Nuking?

**Comment by triniwiz** [comment]
Around the community we use the term nuking which simply means deleting `node_modules, platforms & package-lock.json` then rebuilding

**Comment by alexrainman** [comment]
Glad you told me. I was about to grab some C4 to blow my mac the hell off ...

**Comment by alexrainman** [comment]
Nuking the project helped but i am facing another issue: placeholder is not showing in Android.
My project use Angular and images folder inside app folder.

**Comment by triniwiz** [comment]
code ? also a good measure when adding assets to your project you can nuke the platforms directory

**Comment by alexrainman** [comment]
I already did that.
There's nothing complicated on my code. I am just using the plugin on RadListView cell to load a web image.
I also noticed that images are not cached. As i scroll up and down the list, the are reloaded from backend, or at least it looks like that.
But, if i populate the list with other items and then with the previous ones, images are loaded from cache.

**Comment by triniwiz** [comment]
To verify it's loading from the cache you can disable the device network connections

**Comment by alexrainman** [comment]
It seems to be loading from cache but it is doing the same effect as it is loading from remote but, only the very first time the list is populated with that data set.

If i populate it with other data set and then go back to he previous one, images load faster.

**Comment by alexrainman** [comment]
I can provide a video.

**Comment by triniwiz** [comment]
If you set the width and height does the same thing happen ?

**Comment by alexrainman** [comment]
Actually i am setting width and height.

```xml
<ImageCacheIt height="50" width="50" borderRadius="25" placeHolder="~/images/profile.png" errorHolder="~/images/profile.png" [imageUri]="my_server_url"></ImageCacheIt>
```

**Comment by triniwiz** [comment]
try 
```xml
<ImageCacheIt resize="50,50" borderRadius="25" placeHolder="~/images/profile.png" errorHolder="~/images/profile.png" [imageUri]="my_server_url"></ImageCacheIt>```

**Comment by alexrainman** [comment]
Same problem.

**Comment by alexrainman** [comment]
Not placeholder and images are not cached while i scroll or at least it looks like that.

**Comment by triniwiz** [comment]
Can you share what the item template looks like ?

**Comment by alexrainman** [comment]
Here you have:

```xml
    <RadListView [items]="employees" height="80">
        <ng-template tkListItemTemplate let-employee="item">
            <StackLayout orientation="vertical" width="80">
                <ImageCacheIt height="50" width="50" borderRadius="25" placeHolder="~/images/profile.png" errorHolder="~/images/profile.png" [imageUri]="image_server_url"></ImageCacheIt>
                <Label [text]="employee.FirstName + ' ' + employee.LastName" fontSize="10" textWrap="true" textAlignment="center"></Label>
            </StackLayout>
        </ng-template>
        <ListViewLinearLayout tkListViewLayout scrollDirection="Horizontal"></ListViewLinearLayout>
    </RadListView>
```

**Comment by triniwiz** [comment]
Thank you I'll add an example to the demo using so I can try reproducing

**Comment by bjai** [comment]
any update i am also getting the same issue

**Comment by msl2000** [comment]
Okay nuking it solved the issue :D

**Comment by mwalilu** [comment]
Nuking worked! Thanks :-)

**Comment by triniwiz** [comment]
Moved away from picasso so no more of this 🙃
