### ISSUE TITLE
Handler broken image error

### ISSUE THREAD

**Issue by saulosda** [triniwiz/nativescript-image-cache-it#62]
Hi,

My app works fine using this plug-in but if the image is corrupted over http the app crashes. Is there a way to handler broken image, 0k size, wrong extension and so on errors? 

See below stacktrace on Android..

An uncaught Exception occurred on "pool-9-thread-1" thread.
com.bumptech.glide.load.resource.gif.GifDrawable cannot be cast to android.graphics.drawable.BitmapDrawable

StackTrace:
java.lang.ClassCastException: com.bumptech.glide.load.resource.gif.GifDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
	at com.github.triniwiz.imagecacheit.ImageView$1$1.run(ImageView.java:407)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

**Comment by triniwiz** [comment]
Not a broken image case but it was addressed 😄

**Comment by saulosda** [comment]
😄 lol.. goal achieved. thks man!
