### ISSUE TITLE
:buildMetadata Exception in thread "main" java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by friedolinfoerder** [triniwiz/nativescript-image-cache-it#8]
When I add the plugin and build the my project (tns run android), I get the following error message:

```
:buildMetadata
Exception in thread "main" java.lang.IllegalArgumentException: Class com.squareup.picasso.ContentStreamRequestHandler conflict: ~/.gradle/caches/modules-2/files-2.1/com.squareup.picasso/picasso/2.5.2/7446d06ec8d4f7ffcc53f1da37c95f200dcb9387/picasso-2.5.2.jar and ~/git/nativeTest/spotwild-app/node_modules/nativescript-image-cache-it/platforms/android/picasso-2.5.2.jar
	at com.telerik.metadata.ClassRepo.cacheJarFile(ClassRepo.java:21)
	at com.telerik.metadata.Builder.build(Builder.java:39)
	at com.telerik.metadata.Generator.main(Generator.java:44)
:buildMetadata FAILED
```

It tried almost everything:
* tns platform remove android -> tns platform add android
* remove folder ~/.gradle/caches
* remove folder platforms/android/build
* tns platform android clean
* installed different versions of android apks and tried the build with them

When I remove the local picasso-2.5.2.jar (after a failed build) it's working fine, but it seems there are missing resource values, which are there without the plugin like the "com.google.android.geo.API_KEY".
It looks like it's some kind of strange caching problem. 

My current setup:
Nativescript 2.3
Android SDK 23
Android Build-Tools 23.0.3
Android Platform Tools 25
Android SDK Tools 25.2.2
Android Support Repository 39
Google Play Services 37
Google Repository 38

Any ideas, any thoughts? thanks in advance

**Comment by ADjenkov** [comment]
Can confirm the exceptions on VanillaJS {N} 2.5 Android..The plugin is not working at all even with local images (crashes witouth binding).
