### ISSUE TITLE
Can't find variable: ImageCacheItUtils (iOS crash)

### ISSUE THREAD

**Issue by rrr3da** [triniwiz/nativescript-image-cache-it#82]
### Which platform(s) does your issue occur on?
- iOS both emulator and device

### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.0.10
- Cross-platform modules: 6.5.20
- Runtime(s): 6.5.3
- Plugin(s):
```
  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript/theme": "~2.3.3",
    "@nstudio/nativescript-loading-indicator": "^4.0.0",
    "@types/lodash": "^4.14.162",
    "email-validator": "^2.0.4",
    "humanize-duration": "^3.24.0",
    "lodash": "^4.17.20",
    "moment": "^2.29.1",
    "nativescript-algolia": "^1.2.3",
    "nativescript-angular": "~8.21.0",
    "nativescript-carousel": "^6.1.1",
    "nativescript-exoplayer": "^4.0.2",
    "nativescript-geolocation": "^5.1.0",
    "nativescript-gif": "^4.0.6",
    "nativescript-google-maps-sdk": "^2.9.1",
    "nativescript-image-cache-it": "^6.3.5",
    "nativescript-image-zoom": "^3.0.3",
    "nativescript-imagecropper": "^3.0.0",
    "nativescript-imagepicker": "^7.1.0",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-photoviewer": "^2.1.5",
    "nativescript-plugin-firebase": "^10.5.2",
    "nativescript-ui-listview": "^8.2.0",
    "reflect-metadata": "~0.1.13",
    "rxjs": "^6.6.3",
    "tns-core-modules": "~6.5.20",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@ngtools/webpack": "~8.2.0",
    "codelyzer": "~4.5.0",
    "nativescript-dev-webpack": "~1.5.1",
    "node-sass": "^4.14.1",
    "tns-android": "6.5.3",
    "tns-ios": "6.5.3",
    "tns-platform-declarations": "^6.5.15",
    "tslint": "~5.19.0",
    "typescript": "~3.5.3"
  },
```

### Please, tell us how to recreate the issue in as much detail as possible. 
The problem seems to arise after I installed nativescript-image-zoom and nativescript-carousel, needed for the Android-side of the project.
Before the issue, I was fine using nativescript-image-cache-it 6.0.6.
Now, even if I revert back to previous package.json (no nativescript-image-zoom, no nativescript-carousel, nativescript-image-cache-it 6.0.6), the problem keeps showing.

**JS ERROR ReferenceError: Can't find variable: ImageCacheItUtils**

As soon as I have a RadListView to show, the app unexpectedly quits showing this error (taken from terminal, running on a real iOS device (iPhone XR)

```
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x10580a348 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x105844434 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x1063af388 ffi_closure_SYSV_inner
4   0x1063b01b4 .Ldo_closure
5   0x106898fc4 -[TKListView collectionView:cellForItemAtIndexPath:]
6   0x18769c058 <redacted>
7   0x1876a0e48 <redacted>
8   0x1876a5690 <redacted>
9   0x188489dd4 <redacted>
10  0x188993280 <redacted>
11  0x18899373c <redacted>
12  0x1889a7b64 <redacted>
13  0x1888ef114 <redacted>
14  0x18891a418 <redacted>
15  0x18891b778 <redacted>
16  0x1855be444 <redacted>
17  0x1855b8858 <redacted>
18  0x1855b8e08 <redacted>
19  0x1855b84bc CFRunLoopRunSpecific
20  0x19c03d820 GSEventRunModal
21  0x187f5c734 <redacted>
22  0x187f61e10 UIApplicationMain
23  0x1063b0044 ffi_call_SYSV
24  0x1063aeae8 ffi_call_int
25  0x1063ae648 ffi_call
26  0x1057cd3d8 NativeScript::FunctionWrapper::call(JSC::ExecState*)
27  0x10637bb10 llint_entry
28  0x106378f28 llint_entry
29  0x106378f28 llint_entry
30  0x106378f28 llint_entry
31  0x106378f28 llint_entry
JavaScript stack trace:
file: node_modules/nativescript-image-cache-it/image-cache-it.ios.js:61:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:511:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:553:0
at file: node_modules/@nativescript/core/ui/layouts/layout-base-common.js:125:0
at file: node_modules/@nativescript/core/ui/core/view/view-common.js:925:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:552:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:553:0
at file: node_modules/@nativescript/core/ui/layouts/layout-base-common.js:125:0
at file: node_modules/@nativescript/core/ui/core/view/view-common.js:925:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:552:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:553:0
at file: node_modules/@nativescript/core/ui/layouts/layout-base-common.js:125:0
at file: node_modules/@nativescript/core/ui/core/view/view-common.js:925:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:552:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:448:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:437:0
at file: node_modules/nativescript-ui-listview/ui-listview.ios.js:1954:0
at file: node_modules/nativescript-ui-listview/ui-listview.ios.js:662:0
at UIApplicationMain([native code])
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file: node_modules/@nativescript/angular/platform-common.js:210:0
at file: node_modules/@nativescript/angular/platform-common.js:111:0
at file: node_modules/@nativescript/angular/platform-common.js:91:0
at file:///app/bundle.js:7617:144
at ./main.ts(file:///app/bundle.js:7622:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(f<\M-b\M^@\M-&>
JavaScript error:
file: node_modules/nativescript-image-cache-it/image-cache-it.ios.js:61:0: JS ERROR ReferenceError: Can't find variable: ImageCacheItUtils
*** JavaScript call stack:
(
0   UIApplicationMain@[native code]
1   run@file: node_modules/@nativescript/core/application/application.ios.js:312:0
2   @file: node_modules/@nativescript/angular/platform-common.js:210:0
3   @file: node_modules/@nativescript/angular/platform-common.js:111:0
4   @file: node_modules/@nativescript/angular/platform-common.js:91:0
5   @file:///app/bundle.js:7617:144
6   ./main.ts@file:///app/bundle.js:7622:34
7   __webpack_require__@file: src/webpack/bootstrap:750:0
8   checkDeferredModules@file: src/webpack/bootstrap:43:0
9   webpackJsonpCallback@file: src/webpack/bootstrap:30:0
10  anonymous@file:///app/bundle.js:2:61
11  evaluate@[native code]
12  moduleEvaluation@:1:11
13  @:2:1
14  asyncFunctionResume@:1:11
15  @:24:9
16  promiseReactionJob@:1:11
)
*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: ReferenceError: Can't find variable: ImageCacheItUtils
at
file: node_modules/nativescript-image-cache-it/image-cache-it.ios.js:61:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:511:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:553:0
at file: node_modules/@nativescript/core/ui/layouts/layout-base-common.js:125:0
at file: node_modules/@nativescript/core/ui/core/view/view-common.js:925:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:552:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:553:0
at file: node_modules/@nativescript/core/ui/layouts/layout-base-common.js:125:0
at file: node_modules/@nativescript/core/ui/core/view/view-common.js:925:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:552:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:553:0
at file: node_modules/@nativescript/core/ui/layouts/layout-base-common.js:125:0
at file: node_modules/@nativescript/core/ui/core/view/view-common.js:925:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:552:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:448:0
at file: node_modules/@nativescript/core/ui/core/view-base/view-base.js:437:0
at file: node_modules/nativescript-ui-listview/ui-listview.ios.js:1954:0
at file: node_modules/nativescript-ui-listview/ui-listview.ios.js:662:0
at UIApplicationMain([native code])
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file: node_modules/@nativescript/angular/platform-common.js:210:0
at file: node_modules/@nativescript/angular/platform-common.js:111:0
at file: node_modules/@nativescript/angular/platform-common.js:91:0
at file:///app/bundle.js:7617:144
at ./main.ts(file:///app/bundl<\M-b\M^@\M-&>
NativeScript caught signal 6.
Native Stack:
1   0x105853018 sig_handler(int)
2   0x1ccb9627c <redacted>
3   0x1ccb9bc74 pthread_kill
4   0x18e744bb4 abort
5   0x1997bbe24 <redacted>
6   0x1997ad434 <redacted>
7   0x1996bc710 <redacted>
8   0x1997bb2a8 <redacted>
9   0x1997bdee0 __cxa_get_exception_ptr
10  0x1997bde98 <redacted>
11  0x1996bc558 <redacted>
12  0x10580a820 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
13  0x105844434 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
14  0x1063af388 ffi_closure_SYSV_inner
15  0x1063b01b4 .Ldo_closure
16  0x106898fc4 -[TKListView collectionView:cellForItemAtIndexPath:]
17  0x18769c058 <redacted>
18  0x1876a0e48 <redacted>
19  0x1876a5690 <redacted>
20  0x188489dd4 <redacted>
21  0x188993280 <redacted>
22  0x18899373c <redacted>
23  0x1889a7b64 <redacted>
24  0x1888ef114 <redacted>
25  0x18891a418 <redacted>
26  0x18891b778 <redacted>
27  0x1855be444 <redacted>
28  0x1855b8858 <redacted>
29  0x1855b8e08 <redacted>
30  0x1855b84bc CFRunLoopRunSpecific
31  0x19c03d820 GSEventRunModal
JS Stack:
UIApplicationMain([native code])
at run(file: node_modules/@nativescript/core/application/application.ios.js:312:0)
at file: node_modules/@nativescript/angular/platform-common.js:210:0
at file: node_modules/@nativescript/angular/platform-common.js:111:0
at file: node_modules/@nativescript/angular/platform-common.js:91:0
at file:///app/bundle.js:7617:144
at ./main.ts(file:///app/bundle.js:7622:34)
at __webpack_require__(file: src/webpack/bootstrap:750:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation
at
at asyncFunctionResume
at
at promiseReactionJob
```

I already tried cleaning everything with `tns clean` in every step, but to no avail.

Can you help me with that? Thank you, regards

**Comment by triniwiz** [comment]
A little tip each time you install a new package which contains native code you should try cleaning the project first it seems it may not be picking up the swift class in the plugin

**Comment by rrr3da** [comment]
Thank you!
I did it, sorry I just edited my issue.
The problem keeps showing

**Comment by rrr3da** [comment]
I switched to another branch I used before adding the zoom and carousel plugins.

I run `tns clean` then `tns plugin remove nativescript-image-cache-it` then `tns plugin add nativescript-image-cache-it@6.0.6` then `tns run ios` and the issue is gone. OK 👍

**Comment by rrr3da** [comment]
If i move to the latest version of this plugin by doing `tns plugin remove nativescript-image-cache-it` and then `tns plugin add nativescript-image-cache-it`, I have the crash.

**Comment by triniwiz** [comment]
Interesting a couple things to try an report back

1. Use the latest version
2. nuke the old way 😀 
Try running again if it fails then continue with the following
3. Open the `metadata-generation-stderr-x86_64.txt` located `your-app/platforms/ios/build/Debug-iphonesimulator/metadata-generation-stderr-x86_64.txt` , search for `ImageCacheItUtils` an paste the surrounding text
4. Open the `.xcworkspace` located `your-app/platforms/ios` then you can try cleaning and building in xcode report back any error

**Comment by rrr3da** [comment]
Hi @triniwiz,
I installed the latest version, then tns run ios, the app crashes, but there's no ImageCacheItUtils inside metadata-generation-stderr-x86_64.txt

**Comment by triniwiz** [comment]
Oh can you confirm the file exists in node_modules for the plugin also your Xcode version

**Comment by rrr3da** [comment]
Sorry, what file should exist?

XCode version: 12.0.1 (12A7300)

**Comment by triniwiz** [comment]
A file named `ImageCacheItUtils.swift` would be in `platforms/ios/src` in of the node module package

**Comment by rrr3da** [comment]
![Screenshot 2020-10-29 at 21 04 13](https://user-images.githubusercontent.com/12610856/97626557-501da200-1a2a-11eb-9057-b58fb69edb05.png)
Yes I have that file under node_modules/nativescript-image-cache-it/platforms/ios/src

**Comment by rrr3da** [comment]
I tried cleaning and building from inside XCode, but I have no errors apparently, only a couple of unrelated warnings

**Comment by triniwiz** [comment]
In XCode do you see something like the following ?
![image](https://user-images.githubusercontent.com/6695919/97627260-7d098f00-1a01-11eb-932c-ebda728b3649.png)

**Comment by rrr3da** [comment]
Yes, exactly those 2 files

**Comment by triniwiz** [comment]
If you remove the zoom an carousel then try building with the latest does it work ?

**Comment by rrr3da** [comment]
No, it doesn't.
I'm trying different versions from 6.0.6 (working) up to the latest and I tell you when it breaks

**Comment by triniwiz** [comment]
If you run the app from xcode does it crash ?

**Comment by rrr3da** [comment]
Between any step `tns plugin remove nativescript-image-cache-it`, `tns plugin add nativescript-image-cache-it@version`, `tns clean` and then `tns ios run`: 

- 6.1.0 -> works
- 6.2.0 -> BREAKS

**Comment by rrr3da** [comment]
apparently, i revert back to 6.0.6 and then it began crashing again.
this is really strange

**Comment by triniwiz** [comment]
Quite interesting 🧐 can you create a v6 project with this plugin only to test but before doing this you can try moving the swift source from `/ios/src` to `/ios` the remove the platforms directory from the app root then rebuild

**Comment by rrr3da** [comment]
I found the issue.
No matter what version I add with `tns plugin add nativescript-image-cache-it@version`, because when I do `tns clean`, and then `tns run ios` then in package_lock.json i have 6.3.5 and the applications crashes.

**Comment by rrr3da** [comment]
If I don't do `tns clean` but just only `tns plugin add nativescript-image-cache-it@6.2.0` I see 6.2.0 in package_lock.json and the application works. So, version 6.2.0 is good as well, in contrast with what I wrote in my comment before

**Comment by rrr3da** [comment]
I confirm that something broke from 6.3.3 and upwards.
App is ok up to 6.3.2

**Comment by triniwiz** [comment]
Thanks there was a publishing issue I think with .3 or .4 I’ll verify things an publish a new version 


Sent from Yahoo Mail for iPhone


On Thursday, October 29, 2020, 5:42 PM, rrr3da <notifications@github.com> wrote:




I confirm that something broke from 6.3.3 and upwards.
App is ok up to 6.3.2

**Comment by triniwiz** [comment]
please update to enjoy the fix 😄

**Comment by rrr3da** [comment]
Thank you
